// Generated by CoffeeScript 1.6.3
(function() {
  var SwitchingTable;

  SwitchingTable = (function() {
    SwitchingTable.tabs = [];

    SwitchingTable.c_tab;

    function SwitchingTable(id, headers_class) {
      this.id = id;
      this.headers_class = headers_class;
      this.populate();
    }

    SwitchingTable.prototype.populate = function() {
      var _this = this;
      this.tabs = $("#" + this.id).find("." + this.headers_class);
      return $(this.tabs).each(function(index, elem) {
        if ($(elem).hasClass("c_tab")) {
          _this.c_tab = elem;
        }
        return $(elem).click(function(e) {
          var c_tabtable_class, n_tabtable_class;
          $(_this.c_tab).removeClass("c_tab");
          c_tabtable_class = $(_this.c_tab).attr("name");
          $("." + c_tabtable_class).fadeOut(400);
          $(elem).addClass("c_tab");
          n_tabtable_class = $(elem).attr("name");
          $("." + n_tabtable_class).fadeIn(400);
          return _this.c_tab = elem;
        });
      });
    };

    return SwitchingTable;

  })();

  $(document).ready(function() {
    var partners_table;
    return partners_table = new SwitchingTable("partners_table", "pt_header");
  });

}).call(this);
