// Generated by CoffeeScript 1.6.3
(function() {
  var RoundSwitcher;

  RoundSwitcher = (function() {
    RoundSwitcher.elem_list = [];

    RoundSwitcher.c_index;

    function RoundSwitcher(container_id, elem_class, active_class) {
      this.container_id = container_id;
      this.elem_class = elem_class;
      this.active_class = active_class;
      this.populate_list();
    }

    RoundSwitcher.prototype.populate_list = function() {
      var container,
        _this = this;
      container = $("#" + this.container_id);
      this.elem_list = $(container).find("." + this.elem_class);
      this.elem_count = this.elem_list.length;
      return $(this.elem_list).each(function(index, elem) {
        if ($(elem).hasClass("" + _this.active_class) === true) {
          _this.c_index = index;
          return $(elem).find("img").fadeIn(400);
        }
      });
    };

    RoundSwitcher.prototype.switch_right = function() {
      var c_element, new_element, new_index;
      c_element = this.elem_list[this.c_index];
      new_index = this.c_index - 1;
      if (new_index < 0) {
        new_index = this.elem_count - 1;
      }
      new_element = this.elem_list[new_index];
      $(c_element).find("img").fadeOut(400);
      $(c_element).removeClass("" + this.active_class);
      $(new_element).find("img").fadeIn(400);
      $(new_element).addClass("" + this.active_class);
      return this.c_index = new_index;
    };

    RoundSwitcher.prototype.switch_left = function() {
      var c_element, new_element, new_index;
      c_element = this.elem_list[this.c_index];
      new_index = this.c_index + 1;
      if (new_index === this.elem_count) {
        new_index = 0;
      }
      new_element = this.elem_list[new_index];
      $(c_element).find("img").fadeOut(400);
      $(c_element).removeClass("" + this.active_class);
      $(new_element).find("img").fadeIn(400);
      $(new_element).addClass("" + this.active_class);
      return this.c_index = new_index;
    };

    return RoundSwitcher;

  })();

  $(document).ready(function() {
    var diploma_switcher, partners_switcher;
    diploma_switcher = new RoundSwitcher("rspm", "diploma", "d_current");
    $("#rspm").find(".arrow_right").click(function() {
      return diploma_switcher.switch_right();
    });
    $("#rspm").find(".arrow_left").click(function() {
      return diploma_switcher.switch_left();
    });
    partners_switcher = new RoundSwitcher("partners", "p_award", "p_current");
    $("#partners").find(".arrow_right").click(function() {
      return partners_switcher.switch_right();
    });
    return $("#partners").find(".arrow_left").click(function() {
      return partners_switcher.switch_left();
    });
  });

}).call(this);
